var img_dict = {
    0: ["lockdown1_small.jpg","LOCKDOWN", "by Barbara Gigerl"],
    1: ["homeoffice_4_small.jpg", "HOME OFFICE. Ich habe in vielen Betrieben eine unfassbare Professionalität erlebt, ganz detaillierte Präventionskonzepte, starke Vorsichtsmaßnahmen, Regelungen für die Produktionsstätten genauso wie für den Pausenbereich.", "Sebastian Kurz, \"Pressestatements nach dem Treffen mit den Sozialpartnern\", 13.09.2020"],
    2: ["systemrelevant_3_small.jpg", "SYSTEMRELEVANT. Diensträder und Teameinteilungen sollten so verändert werden, dass im Erkrankungsfall einer Mitarbeiterin/ eines Mitarbeiters, möglichst wenige Kolleginnen und Kollegen einem entsprechenden Kontaktpersonenmanagement unterzogen werden müssen", "Bundesministerium für Soziales, Gesundheit, Pflege und Konsumentenschutz \"Empfehlung zu COVID-19 Schutzmaßnahmen für Krankenanstalte\", 30.03.2020"],
    3: ["mund_nasen_schutz_1_small.jpg", "MUND-NASEN-SCHUTZ. Wir bitten Sie zum Schutz aller BesucherInnen und MitarbeiterInnen folgende Regeln während Ihres Besuchs in der ALBERTINA einzuhalten. Bitte tragen Sie zum Schutz Ihrer Mitmenschen eine Mund-Nasen-Maske.", "Albertina, \"Regeln für Ihren Museumsbesuch\", abgerufen am 14.11.2020"],
    4: ["zweite_welle3_small.jpg", "ZWEITE WELLE. Es ist der Aufenthalt im Freien zur sportlichen Betätigung erlaubt, oder wenn es einem einfach nicht gut geht, die Decke auf den Kopf zu fliegen droht und man einfach raus muss.", "Karl Nehammer, \"Schärfere CoV-Maßnahmen ab Dienstag\", Pressekonferenz vom 31.10.2020"],
    5: ["quarantäne_2_small.jpg", "QUARANTÄNE. Da sich die Person in der Inkubationszeit befinden kann, muss auch bei einem negativen Testergebnis die Quarantäne bis zum Tag 10 nach dem letzten Kontakt zur positiv getesteten Person aufrecht bleiben.", "Bundesministerium für  Soziales, Gesundheit, Pflege  und Konsumentenschutz, \"Informationen für Kontaktpersonen\", 02.11.2020"],
    6: ["distancelearning4_small.jpg","DISTANCE LEARNING. Nutzen Sie die gekennzeichneten Sitzplätze um ausreichend Abstand nach allen Seiten sicherzustellen. Die physische Anwesenheit der Vortragenden in den Hörsälen ist auf ein Mindestmaß zu reduzieren."],
    7: ["verdachtsfall2_small.jpg", "VERDACHTSFALL. Die Spekulationen über einen Zusammenhang zwischen 5G in Wuhan und des dortigen Virus-Ausbruches scheinen Fakt zu sein. Denn die aktuelle Pandemie ist zeitgleich mit der neuen Funktechnologie 5G entstanden.", "freeworldnews.us, \"5G führt zu Blutgerinnung und Sauerstoffmangel\",(129.8k Views) 25.06.2020"],
    8: ["reisebeschraenkungen2_small.jpg", "REISEBESCHRÄNKUNGEN. Aufgrund der Ausbreitung des Coronavirus (COVID-19) rät das Außenministerium dringend von allen nicht notwendigen Reisen ab. Zudem kann auch die Sicherheit der Gesundheitsversorgung in zahlreichen Ländern nicht mehr gewährleistet werden.", "Bundesministerium für europäische und internationale Angelegenheiten, abgerufen am 02.11.2020"], 
    9: ["selbstisolation_1_small.jpg", "SELBSTISOLATION. Häusliche Isolation und Quarantäne sind Ausnahmesituationen, welche die meisten Menschen noch nicht erlebt haben. Diese gesetzten Maßnahmen können auf die Psyche einwirken und für Betroffene sehr belastend sein.", "Berufsverband Österreichischer PsychologInnen. \"COVID-19: Wie Sie häusliche Isolation und Quarantäne gut überstehen\", 17.03.2020"],
    10: ["social_distancing2_small.jpg", "SOCIAL DISTANCING. Wir müssen unser soziales Leben in Österreich auf ein Minimum reduzieren damit wir es schaffen dass es irgendwann zu einer Abflachung der Ansteckungsquelle kommt.", "Sebastian Kurz, \"ZIB Spezial zur Coronavirus-Situation\", 12.03.2020"],
    11: ["kk2_5_small.jpg", "KONTAKTPERSON KATEGORIE 2. Versorgungskritisches Gesundheits- und Schlüsselpersonal, dass als Kategorie I-Kontaktperson klassifiziert wurde, darf nur dann außerhalb des Wohnortes weiterarbeiten, wenn auf Grund des gesundheitlichen Zustands kein Hinweis auf COVID-19 vorliegt.", "Bundesministerium für  Soziales, Gesundheit, Pflege  und Konsumentenschutz, \"Empfehlung zum Umgang mit SARS-CoV-2 Kategorie I Kontaktpersonen bei versorgungskritischem Gesundheits- und Schlüsselpersonal\", 20.11.2020"],
    12: ["abstandsregelung_2_small.jpg", "ABSTANDSREGELUNG. Wir können auch den 2.Teil der Pandemie gut bewältigen! Schutz ist einfach: Hygienemassnahmen, Mindestabstand, MNS wo erforderlich, dichte Menschenansammlungen meiden, regelmäßig lüften.", "Rudolf Anschober, Tweet vom 10.10.2020"],
    13: ["contact_tracing2_small.jpg", "CONTACT TRACING. Sowohl die \"Vorwärts-Ermittlung\" der von einem bestätigten Fall ausgehenden, möglichen Übertragungen, als auch die \"Rückwärts-Ermittlung\" (Infektionsquellensuche) sind von Bedeutung.", "RKI. \"Kontaktpersonennachverfolgung bei respiratorischen Erkrankungen durch das Coronavirus SARS-CoV-2\", 19.10.2020"],
    14: ["absonderungsbescheid4_small.jpg","ABSONDERUNGSBESCHEID. Zum Schutz vor der Weiterverbreitung von SARS-CoV-2 (\"neuartiges Coronavirus\") wird XXX mit 29.10.2020 abgesondert. Sie dürfen den Absonderungsort bis zur Verständigung über das Vorliegen des negativen Testergebnisses nicht verlassen und müssen Kontakt zu anderen Personen meiden."],
    15: ["clusterbildung1_small.jpg", "CLUSTERBILDUNG. Als Veranstaltung gelten insbesondere geplante Zusammenkünfte und Unternehmungen zur Unterhaltung, Belustigung, körperlichen und geistigen Ertüchtigung und Erbauung. Dazu zählen kulturelle Veranstaltungen, Sportveranstaltungen, Hochzeitsfeiern, Geburtstagsfeiern, Jubiläumsfeiern, Filmvorführungen, Fahrten mit Reisebussen oder Ausflugsschiffen zu touristischen Zwecken, Ausstellungen, Kongresse, Fach-und Publikumsmessen und Gelegenheitsmärkte.", "BGBl. II -Ausgegeben am 1. November 2020 -Nr. 463, 01.11.2020"]
};